### ISSUE TITLE
RazorLight is not supported

### ISSUE THREAD

**Issue by Almeonamy** [lukencode/FluentEmail#140]
RazorLight is not supported library and it is in beta yet. It doesn't work on .Net Framework 4.7.1. May be is there any other renderers?

**Comment by michielpeeters** [comment]
If you want to make use of the FluentEmail package you should thick in the nuget package manager include prerelease, install the razorlight beta1 package and than install fluentemail. Only there is a new problem that the author of RazorLight have removed the backwards compatibility for the old .csproj files (.net framework <=4.7.2) which results in exceptions. If you want to make it work until it has been fixed you need to clone the RazorLight repository (the fix is included in the master brach) and clone FluentEmail because FluentEmail needs to be updated with the new methods from the RazorLightEngine. Include these DLL's into your project (i know, yuck ... :P) but now everything works :-).

**Comment by Almeonamy** [comment]
That does not suit me. In the result I used old RazorEngine. But thank you for your solution.
