### ISSUE TITLE
System.Net.Mail.SmtpClient is deprecated

### ISSUE THREAD

**Issue by mtrutledge** [lukencode/FluentEmail#156]
The SmtpClient class is now deprecated and MS recommends using MailKit / MimeKit instead.

https://docs.microsoft.com/en-us/dotnet/api/system.net.mail.smtpclient?view=netcore-2.2

**Comment by mtrutledge** [comment]
It would probably be best to add a new MailKit Sender implementation for backwards compatibility.

**Comment by mtrutledge** [comment]
PR Submitted to add a new MailKit Sender

**Comment by Davilink** [comment]
It would be nice to update the readme for promoting `FluentEmail.MailKit` instead of `FluentEmail.Smtp` and maybe change the readme on the nuget package of the `FluentEmail.Smtp` to warn user to move to `FluentEmail.MailKit` instead of
![image](https://user-images.githubusercontent.com/1498932/156621141-6806dd7f-2569-45f7-9a30-400e670880e5.png)
