### ISSUE TITLE
Method not found - FluentEmail.MailKit

### ISSUE THREAD

**Issue by xts-velkumars** [lukencode/FluentEmail#357]
Hi @lukencode, 

I'm getting exception while using AddMailKitSender. Below is the code

**Method not found: 'System.Threading.Tasks.Task MailKit.MailTransport.SendAsync(MimeKit.MimeMessage, System.Threading.CancellationToken, MailKit.ITransferProgress)'.
I have injected like below** 

```
 services
            .AddFluentEmail(fromEmailAddress)
            .AddMailKitSender(new SmtpClientOptions
            {
                Server = server,
                Port = port,
                Password = password,
                UseSsl = enableSsl,
                User = from,
                RequiresAuthentication = useDefaultCredentials
            });
```

```
 var response = await mailer
                .To(notificationInfo.To.JoinWithSemiColon())
                .Subject(notificationInfo.Subject)
                .Body(notificationInfo.Body)
                .SendAsync();
```
![image](https://user-images.githubusercontent.com/13570225/210317446-20f8b196-0421-4944-88d5-4c934a3a2979.png)

**Comment by carlin010** [comment]
I just ran into this issue and found I had both FluentEmail.MailKit (version 3.0.2) and MailKit (v3.0+) were installed as package references in my project. 

Removing MailKit (v3.0+) from my package references resolved the issue. This is because of FluentEmail.MailKit's dependency on MailKit v2.10.1 and MimeKit v2.10.1. If you have MailKit installed separately, I am assuming FluentEmail.MailKit attempts to use v3.0+ instead of the dependent version. 

I hope this helps.

**Comment by xts-velkumars** [comment]
@carlin010, Thank you so much. Obsoletely right. 

After I removed MailKit reference. Its working as excepted
